### ISSUE TITLE
feature request： Add the function of downloading subtitles generated by buttercup-chrome

### ISSUE THREAD

**Issue by jpACGlover** [iGerman00/buttercup-chrome#2]

**Comment by iGerman00** [comment]
Added in https://github.com/iGerman00/buttercup-chrome/commit/ec9a7e8eb4fe46a60d72cfff7d7987559d360396.

Usage: 
1. Open extension
2. Turn on `Download SRT`
3. Click the caption button (you might need to click it again if it was already active so that it requests again)
