### ISSUE TITLE
Partially working on Ungoogled Chromium.

### ISSUE THREAD

**Issue by clacheek** [iGerman00/buttercup-chrome#3]
Neat idea of an extension but It seems to only transcribe in the original language and doesn't support translation to English, even after forcing auto-translate (russian>english). The extension hasn't prompted me with any errors to embed on this post, so I don't know what could be the issue. I've only tested it on Ungoogled Chromium; it might work on the usual Chrome, but I won't use that. I'm already compromising by using Ungoogled Chromium just because of this extension alone. A port for Firefox based browsers would be great tho. Thanks!

**Comment by iGerman00** [comment]
The English translation is handled by the whisper API, and has to be toggled on in the extension settings since it is cached separately. Are you sure that's on? Don't forget to also refresh your YouTube page after changing Buttercup settings. You only need to toggle the Buttercup option in the subtitles menu - pressing the CC button should be enough.

**Comment by clacheek** [comment]
> The English translation is handled by the whisper API, and has to be toggled on in the extension settings since it is cached separately. Are you sure that's on? Don't forget to also refresh your YouTube page after changing Buttercup settings. You only need to toggle the Buttercup option in the subtitles menu - pressing the CC button should be enough.

~~Checked, everything is set up as you mentioned, still not working properly. This time, I tested on regular Chrome and, "thankfully," encountered this error, so you can investigate further to determine what's going on.~~ 
Solved it, sorry for the inconvenience. I'll say that I would love a port for Firefox. Thanks for the extension!
